### ISSUE TITLE
Release 2.0.1 seems to be missing code, it cannot handle partial/fractional shares but run locally it can.

### ISSUE THREAD

**Issue by AC0DEM0NK3Y** [EmilMaric/cad-capital-gains#33]
Schwab for eg. allows for partial shares to be bought/sold which some companies will do for RSU awards.

This won't handle it "Error: The quanitity entered 42.66 is not an integer"

**Comment by AC0DEM0NK3Y** [comment]
OK yes, there is an issue with your 2.0.1 release it seems. If I run the code locally via poetry it works fine, same input file ran on the installed version it fails with the error in the first post.

I'm changing the title to match the new info,

**Comment by EmilMaric** [comment]
@AC0DEM0NK3Y Sorry for the really late response on this, somehow I missed this. I will take a look this week to see if I can fix this.

**Comment by EmilMaric** [comment]
I realize the issue was after pushing the changes in #25, I never released these changes, so 2.0.1 won't have support for partial shares.

I've pushed a PR for creating a new release (`v2.0.2`) that should include the changes for supporting partial shares. There are just some issues with the build system (TravisCI) that I'm sorting out right now, but once that is figured out, then we can complete the release.

As you've already mentioned/discovered, if you run the tool off the head of the `master` branch, you'll have support for partial shares, so I guess that is a temporary workaround for now.

**Comment by EmilMaric** [comment]
I've pushed a new release 2.0.2 that should now support partial shares. Please let me know if you encounter any issues.
